name: ebola_response_app
description: An app for WHO to manage Ebola outbreak response in Congo.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase - Updated to compatible versions
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  google_sign_in: ^6.3.0

  # State Management
  provider: ^6.1.5

  # UI and Functionality
  google_maps_flutter: ^2.12.3
  image_picker: ^1.1.2
  fl_chart: ^0.66.2
  intl: ^0.20.2

  # PDF Generation
  pdf: ^3.11.3
  path_provider: ^2.1.5
  open_file: ^3.5.4

  # HTTP Requests (for ChatGPT API)
  http: ^1.4.0

  # For managing environment variables (like API keys) securely
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - .env